# El metodo K-means

In [1]:
import numpy as np

In [2]:
data = np.random.random(90).reshape(30,3)
data

array([[0.69992512, 0.96153301, 0.83116058],
       [0.82507225, 0.12395954, 0.70908861],
       [0.43617968, 0.18049898, 0.01925303],
       [0.96308969, 0.95124452, 0.18909471],
       [0.1185541 , 0.6405814 , 0.82217798],
       [0.66011711, 0.6359043 , 0.79033954],
       [0.02267243, 0.52332188, 0.16218789],
       [0.21688192, 0.95770938, 0.59621036],
       [0.55452057, 0.5765259 , 0.28574984],
       [0.278855  , 0.86013533, 0.36288513],
       [0.43304708, 0.96395714, 0.09776862],
       [0.25734811, 0.29179306, 0.56004999],
       [0.39982619, 0.04199847, 0.30664738],
       [0.08970287, 0.15536211, 0.28143753],
       [0.38029878, 0.31167918, 0.79546265],
       [0.80133811, 0.66137397, 0.13999198],
       [0.62262548, 0.56432522, 0.75114932],
       [0.68909443, 0.66166498, 0.48783925],
       [0.12165903, 0.72687266, 0.10097068],
       [0.01019891, 0.16337085, 0.45226479],
       [0.61986881, 0.53601504, 0.48865337],
       [0.80736496, 0.09056258, 0.8504724 ],
       [0.

In [4]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1],data[c2]])
clust_centers

array([[0.80736496, 0.09056258, 0.8504724 ],
       [0.04899199, 0.42709631, 0.66118951]])

In [5]:
from scipy.cluster.vq import vq

In [6]:
vq(data,clust_centers)

(array([1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0]),
 array([0.85920119, 0.14634986, 0.78918121, 1.0965601 , 0.27628257,
        0.56806292, 0.50887591, 0.56032094, 0.64718103, 0.57388613,
        0.86784847, 0.26823208, 0.63014689, 0.46873064, 0.37565221,
        0.91139695, 0.51811658, 0.68676683, 0.63952443, 0.33868209,
        0.6037348 , 0.        , 0.42768012, 0.91549093, 0.        ,
        0.76638959, 0.51965394, 0.84091843, 0.71005875, 0.65105718]))

In [7]:
from scipy.cluster.vq import kmeans

In [8]:
kmeans(data, clust_centers)

(array([[0.70483128, 0.6009534 , 0.43459782],
        [0.21794045, 0.39648704, 0.42009106]]), 0.38192827138655994)

In [9]:
kmeans(data,2)

(array([[0.60452703, 0.7279323 , 0.3863075 ],
        [0.33257388, 0.2513683 , 0.47527999]]), 0.3714802655044771)